<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>WatchMe</RootNamespace>
    <AssemblyName>WatchMe</AssemblyName>
    <Version>1.0.0</Version>
    <Product>WatchMe</Product>
    <Authors>threetwoa</Authors>
    <Copyright>Copyright © 2026 threetwoa</Copyright>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="MdXaml" Version="1.27.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

</Project>
